/* eslint-disable */
export enum Permissions {
    CREATE_ACCOUNT = 'create_account',
    EDIT_ACCOUNT = 'edit_account',
    DETAIL_ACCOUNT = 'detail_account',
    LIST_ACCOUNT = 'list_account',
    CREATE_MEETING = 'create_meeting',
    EDIT_MEETING = 'edit_meeting',
    DETAIL_MEETING = 'detail_meeting',
    LIST_MEETING = 'list_meeting',
    DELETE_MEETING = 'delete_meeting',
    PATICIPATE_MEETING = 'paticipate_meeting',
    VOTING_PROPOSAL = 'voting_proposal',
    EDIT_PROPOSAL = 'edit_proposal',
    LIST_PROPOSAL = 'list_proposal',
    DELETE_PROPOSAL = 'delete_proposal',
    SEND_MAIL_TO_SHAREHOLDER = 'send_mail_to_shareholder',
    LIST_USER_STATUS = 'list_user_status',
    LIST_ROLES = 'list_roles',
    LIST_COMPANY = 'list_company',
    CREATE_COMPANY = 'create_company',
    LIST_SHAREHOLDERS = 'list_shareholders',
}
